apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyvec
  namespace: visdemos
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flyvec
  strategy:
    type: Recreate
  template:
    metadata:
      name: flyvec
      namespace: visdemos
      labels:
        run: flyvec
    spec:
      containers:
        - name: flyvec
          image: us.icr.io/research3/visdemos/hoo/flyvec:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # volumeMounts:
          #   - mountPath: "/app/server/data"
          #     name: cos-data
          resources:
            requests:
              cpu: 1
              memory: 4G
              nvidia.com/gpu: 0
            limits:
              cpu: 1
              memory: 4G
              nvidia.com/gpu: 0
          # env:
          #   - name: PYTORCH_PRETRAINED_BERT_CACHE
          #     value: /app/server/data/models/
      imagePullSecrets:
        - name: all-icr-io
      # volumes:
      #   - name: cos-data
      #     persistentVolumeClaim:
      #       claimName: cos-exbert-osc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flyvec
  name: flyvec
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: flyvec